env: "dev"

http_server:
  host: "localhost"
  port: "8080"
  timeout: "4s"
  idle_timeout: "60s"

database:
  port: "5432"
  host: "localhost"
  name: "poster_test"
  user: "user"
  password: ""

mailer:
  port: "587"
  host: "smtp.example.com"
  sender: "test@gmail.com"
  password: "pass"