version: "2"
sql:
  - schema: "../sql/migrations"
    queries: "../sql/queries"
    engine: "postgresql"
    gen:
      go:
        emit_json_tags: true
        out: "../internal/database"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "timestamptz"
            go_type:
              import: "time"
              type: "Time"
